// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/boa/BoardConfig.tsx": () => import("../components/mockups/boa/BoardConfig.tsx"),
  "./components/mockups/boa/Boards.tsx": () => import("../components/mockups/boa/Boards.tsx"),
  "./components/mockups/boa/Dashboard.tsx": () => import("../components/mockups/boa/Dashboard.tsx"),
  "./components/mockups/boa/Login.tsx": () => import("../components/mockups/boa/Login.tsx"),
  "./components/mockups/boa/MemberEditor.tsx": () => import("../components/mockups/boa/MemberEditor.tsx"),
  "./components/mockups/boa/SessionDetail.tsx": () => import("../components/mockups/boa/SessionDetail.tsx"),
  "./components/mockups/boa/SessionRunner.tsx": () => import("../components/mockups/boa/SessionRunner.tsx")
};
